# CMake generated Testfile for 
# Source directory: /tmp/vllm-region-capture-spec/examples
# Build directory: /tmp/vllm-region-capture-spec/build2/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_cpu_kernel_bench_cli]=] "/home/lu_zero/.local/bin/python3.13" "/tmp/vllm-region-capture-spec/tests/scripts/test_cpu_kernel_bench.py" "/tmp/vllm-region-capture-spec/build2/examples/vllm-cpu-kernel-bench")
set_tests_properties([=[test_cpu_kernel_bench_cli]=] PROPERTIES  _BACKTRACE_TRIPLES "/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;79;add_test;/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;0;")
add_test([=[test_server_help]=] "/tmp/vllm-region-capture-spec/build2/examples/vllm-server" "--help")
set_tests_properties([=[test_server_help]=] PROPERTIES  PASS_REGULAR_EXPRESSION "--max-num-seqs N.*--max-num-batched-tokens N.*--cuda-profile-graph-replays N.*--cuda-profile-graph-batch N.*--benchmark-shutdown-fifo F.*--enable-force-include-usage.*--\\[no-\\]enable-prefix-caching" _BACKTRACE_TRIPLES "/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;207;add_test;/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;0;")
add_test([=[test_server_video_family_unregistered]=] "/tmp/vllm-region-capture-spec/build2/examples/vllm-server" "--model" "/nonexistent-model-dir" "--video-family" "not-a-registered-family")
set_tests_properties([=[test_server_video_family_unregistered]=] PROPERTIES  PASS_REGULAR_EXPRESSION "--video-family 'not-a-registered-family' is not a registered video family. Registered families:.*ltx-2\\.5.*minimax-h3" _BACKTRACE_TRIPLES "/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;220;add_test;/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;0;")
add_test([=[test_server_video_family_registered]=] "/tmp/vllm-region-capture-spec/build2/examples/vllm-server" "--model" "/nonexistent-model-dir" "--video-family" "ltx-2.5" "--tool-call-parser" "definitely-not-a-registered-parser")
set_tests_properties([=[test_server_video_family_registered]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "not a registered video family;unknown argument" PASS_REGULAR_EXPRESSION "unknown tool-call parser \"definitely-not-a-registered-parser\"" _BACKTRACE_TRIPLES "/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;233;add_test;/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;0;")
add_test([=[test_server_video_extra_needs_a_value]=] "/tmp/vllm-region-capture-spec/build2/examples/vllm-server" "--model" "/nonexistent-model-dir" "--video-extra" "dit_config_path")
set_tests_properties([=[test_server_video_extra_needs_a_value]=] PROPERTIES  PASS_REGULAR_EXPRESSION "--video-extra takes KEY=VALUE, got 'dit_config_path'" _BACKTRACE_TRIPLES "/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;246;add_test;/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;0;")
add_test([=[test_server_neither_model_flag]=] "/tmp/vllm-region-capture-spec/build2/examples/vllm-server")
set_tests_properties([=[test_server_neither_model_flag]=] PROPERTIES  PASS_REGULAR_EXPRESSION "--model <dir> is required \\(or --speech-model <dir> for a speech/music-only server\\)" _BACKTRACE_TRIPLES "/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;262;add_test;/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;0;")
add_test([=[test_server_speech_only_reaches_the_speech_load]=] "/tmp/vllm-region-capture-spec/build2/examples/vllm-server" "--speech-model" "/nonexistent-speech-dir")
set_tests_properties([=[test_server_speech_only_reaches_the_speech_load]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "--model <dir> is required" PASS_REGULAR_EXPRESSION "--speech-model /nonexistent-speech-dir" _BACKTRACE_TRIPLES "/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;273;add_test;/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;0;")
add_test([=[test_server_speech_family_still_needs_a_checkpoint]=] "/tmp/vllm-region-capture-spec/build2/examples/vllm-server" "--model" "/nonexistent-model-dir" "--speech-family" "minimax-music3")
set_tests_properties([=[test_server_speech_family_still_needs_a_checkpoint]=] PROPERTIES  PASS_REGULAR_EXPRESSION "--speech-family names a family but --speech-model names no checkpoint" _BACKTRACE_TRIPLES "/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;282;add_test;/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;0;")
add_test([=[test_server_speculative_rejects_probabilistic_draft]=] "/tmp/vllm-region-capture-spec/build2/examples/vllm-server" "--model" "/nonexistent-model-dir" "--speculative-config" "{\"method\":\"dspark\",\"model\":\"d\",\"num_speculative_tokens\":7,\"draft_sample_method\":\"probabilistic\"}")
set_tests_properties([=[test_server_speculative_rejects_probabilistic_draft]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "model path is not a directory" PASS_REGULAR_EXPRESSION "speculative-config: draft_sample_method \"probabilistic\" is not implemented.*SPEC-ACCEPT-VARIANTS" _BACKTRACE_TRIPLES "/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;300;add_test;/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;0;")
add_test([=[test_server_speculative_rejects_a_misspelled_key]=] "/tmp/vllm-region-capture-spec/build2/examples/vllm-server" "--model" "/nonexistent-model-dir" "--speculative-config" "{\"method\":\"mtp\",\"num_speculatve_tokens\":7}")
set_tests_properties([=[test_server_speculative_rejects_a_misspelled_key]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "model path is not a directory" PASS_REGULAR_EXPRESSION "speculative-config: unknown key \"num_speculatve_tokens\"" _BACKTRACE_TRIPLES "/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;310;add_test;/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;0;")
add_test([=[test_server_speculative_accepts_a_valid_config]=] "/tmp/vllm-region-capture-spec/build2/examples/vllm-server" "--model" "/nonexistent-model-dir" "--speculative-config" "{\"method\":\"mtp\",\"num_speculative_tokens\":1}")
set_tests_properties([=[test_server_speculative_accepts_a_valid_config]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "speculative-config" PASS_REGULAR_EXPRESSION "model path is not a directory: /nonexistent-model-dir" _BACKTRACE_TRIPLES "/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;321;add_test;/tmp/vllm-region-capture-spec/examples/CMakeLists.txt;0;")
