#!/usr/bin/env python3
"""Generate the Kolibri-1 safetensors tensor manifest (.inc).

Reads the checkpoint directory's shard headers ONLY (the u32-LE header length
+ JSON prefix of each .safetensors file) — no weight bytes — and emits
tests/vllm/models/kolibri1_manifest.inc: per-tensor name, dtype, and shape,
plus scalar census constants. Follows the qwen38_27b_*_manifest.inc pattern.

Usage:
  python3 scripts/gen-kolibri1-manifest.py /mnt/models/Aleph-Alpha/Kolibri-1
"""

import json
import struct
import sys
from collections import Counter
from pathlib import Path

GUARD = """// GENERATED by scripts/gen-kolibri1-manifest.py — DO NOT EDIT BY HAND.
//
// Tensor manifest of the REAL Aleph-Alpha/Kolibri-1 checkpoint: names,
// dtypes and shapes only — no weight bytes. Captured from the shard headers
// of the 32-shard safetensors index (MODEL-TEXT-kolibri-1 W1,
// .agents/specs/kolibri1-1-cpu.md records the checkpoint). See
// tests/vllm/models/test_kolibri1.cpp.
#pragma once

#include <cstdint>

namespace vllm_test {
"""


def read_header(path: Path):
    with path.open("rb") as f:
        (n,) = struct.unpack("<Q", f.read(8))
        return json.loads(f.read(n))


def main() -> int:
    model_dir = Path(sys.argv[1])
    index = json.loads(
        (model_dir / "model.safetensors.index.json").read_text()
    )
    weight_map = index["weight_map"]

    shards = sorted(set(weight_map.values()))
    tensors = []  # (name, dtype, shape) in shard order, name-sorted per shard
    for shard in shards:
        header = read_header(model_dir / shard)
        for name, entry in header.items():
            if name == "__metadata__":
                continue
            tensors.append((name, entry["dtype"], entry["shape"]))

    dtype_counts = Counter(t[1] for t in tensors)
    scale_count = sum(1 for t in tensors if t[0].endswith(".weight_scale_inv"))
    weight_count = sum(1 for t in tensors if t[0].endswith(".weight"))
    expert_count = sum(1 for t in tensors if ".mlp.experts." in t[0])

    out = [GUARD]
    out.append(
        f"inline constexpr int64_t kKolibri1TotalSize = "
        f"{index['metadata']['total_size']};\n"
    )
    out.append(
        f"inline constexpr int64_t kKolibri1TensorCount = {len(tensors)};\n"
    )
    out.append(
        f"inline constexpr int64_t kKolibri1ScaleCount = {scale_count};\n"
    )
    out.append(
        f"inline constexpr int64_t kKolibri1WeightCount = {weight_count};\n"
    )
    out.append(
        f"inline constexpr int64_t kKolibri1ExpertTensorCount = "
        f"{expert_count};\n"
    )
    out.append(f"inline constexpr int64_t kKolibri1ShardCount = {len(shards)};\n\n")
    out.append("struct Kolibri1ManifestTensor {\n  const char* name;\n"
               "  const char* dtype;\n  int64_t shape[2];\n  int rank;\n};\n\n")
    out.append("inline constexpr Kolibri1ManifestTensor kKolibri1Tensors[] = {\n")
    for name, dtype, shape in sorted(tensors):
        dims = ", ".join(str(d) for d in shape)
        if len(shape) == 1:
            dims += ", 0"
        elif len(shape) == 0:
            dims = "0, 0"
        out.append(
            f'    {{"{name}", "{dtype}", {{{dims}}}, {len(shape)}}},\n'
        )
    out.append("};\n\n}  // namespace vllm_test\n")
    sys.stdout.write("".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
